### PR TITLE
Add doubleplus-numbers annotator

### PR DESCRIPTION
**Pull request by anseljh**
Feel free to bounce this if I screwed anything up!

### CODE REVIEW

**Comment by kemitchell** [comment]
Since doubleplus-number exports a fully-fledged annotator, we can actually do this a lot easier! I'll PR to your fork shortly.

**Comment by anseljh** [comment]
I think that should do it...?

**Comment by kemitchell** [comment]
I see the bump to doubleplus-numbers@0.2.0, but we've got 13 commits here. I think you might have rebased your fork onto my pull request, rather than reset to it.

I'm merging by hand now.

**Comment by kemitchell** [comment]
Closed by 2951d80df6f085011673234ea2a6e69bd458412e

**Comment by kemitchell** [comment]
Landed in 0.8.0

**Pull request closed without merging**
